
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef CAN2OBJDICT_H
#define CAN2OBJDICT_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 Can2ObjDict_valueRangeTest (UNS8 typeValue, void * value);
const indextable * Can2ObjDict_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data Can2ObjDict_Data;
extern UNS8 can2_DIData_MC1[7];		/* Mapped at index 0x2000, subindex 0x01 - 0x07 */
extern UNS8 can2_DIData_T[2];		/* Mapped at index 0x2001, subindex 0x01 - 0x02 */
extern UNS8 can2_DIData_M[2];		/* Mapped at index 0x2002, subindex 0x01 - 0x02 */
extern UNS8 can2_DIData_T1[2];		/* Mapped at index 0x2003, subindex 0x01 - 0x02 */
extern UNS8 can2_DIData_T2[2];		/* Mapped at index 0x2004, subindex 0x01 - 0x02 */
extern UNS8 can2_DIData_MC2[7];		/* Mapped at index 0x2005, subindex 0x01 - 0x07 */
extern UNS8 can2_CarData_HMI1[8];		/* Mapped at index 0x2006, subindex 0x01 - 0x08 */
extern UNS8 can2_ATC_DateTime_MC1[6];		/* Mapped at index 0x2007, subindex 0x01 - 0x06 */
extern UNS8 can2_DateTime_HMI1[7];		/* Mapped at index 0x2008, subindex 0x01 - 0x07 */
extern UNS8 can2_DoorData_MC1_12[8];		/* Mapped at index 0x2009, subindex 0x01 - 0x08 */
extern UNS8 can2_DoorData_T_12[8];		/* Mapped at index 0x200A, subindex 0x01 - 0x08 */
extern UNS8 can2_DoorData_M_12[8];		/* Mapped at index 0x200B, subindex 0x01 - 0x08 */
extern UNS8 can2_DoorData_T1_12[8];		/* Mapped at index 0x200C, subindex 0x01 - 0x08 */
extern UNS8 can2_DoorData_T2_12[8];		/* Mapped at index 0x200D, subindex 0x01 - 0x08 */
extern UNS8 can2_DoorData_MC2_12[8];		/* Mapped at index 0x200E, subindex 0x01 - 0x08 */
extern UNS8 can2_ACCData_MC1[8];		/* Mapped at index 0x200F, subindex 0x01 - 0x08 */
extern UNS8 can2_ACCData_T[8];		/* Mapped at index 0x2010, subindex 0x01 - 0x08 */
extern UNS8 can2_ACCData_M[8];		/* Mapped at index 0x2011, subindex 0x01 - 0x08 */
extern UNS8 can2_ACCData_T1[8];		/* Mapped at index 0x2012, subindex 0x01 - 0x08 */
extern UNS8 can2_ACCData_T2[8];		/* Mapped at index 0x2013, subindex 0x01 - 0x08 */
extern UNS8 can2_ACCData_MC2[8];		/* Mapped at index 0x2014, subindex 0x01 - 0x08 */
extern UNS8 can2_BCUData_MC1_1[8];		/* Mapped at index 0x2015, subindex 0x01 - 0x08 */
extern UNS8 can2_BCUData_MC1_2[8];		/* Mapped at index 0x2016, subindex 0x01 - 0x08 */
extern UNS8 can2_BCUData_MC1_3[8];		/* Mapped at index 0x2017, subindex 0x01 - 0x08 */
extern UNS8 can2_BCUData_T_1[8];		/* Mapped at index 0x2018, subindex 0x01 - 0x08 */
extern UNS8 can2_BCUData_T_2[8];		/* Mapped at index 0x2019, subindex 0x01 - 0x08 */
extern UNS8 can2_BCUData_T_3[8];		/* Mapped at index 0x201A, subindex 0x01 - 0x08 */
extern UNS8 can2_BCUData_M_1[8];		/* Mapped at index 0x201B, subindex 0x01 - 0x08 */
extern UNS8 can2_BCUData_M_2[8];		/* Mapped at index 0x201C, subindex 0x01 - 0x08 */
extern UNS8 can2_BCUData_M_3[8];		/* Mapped at index 0x201D, subindex 0x01 - 0x08 */
extern UNS8 can2_BCUData_T1_1[8];		/* Mapped at index 0x201E, subindex 0x01 - 0x08 */
extern UNS8 can2_BCUData_T1_2[8];		/* Mapped at index 0x201F, subindex 0x01 - 0x08 */
extern UNS8 can2_BCUData_T1_3[8];		/* Mapped at index 0x2020, subindex 0x01 - 0x08 */
extern UNS8 can2_BCUData_T2_1[8];		/* Mapped at index 0x2021, subindex 0x01 - 0x08 */
extern UNS8 can2_BCUData_T2_2[8];		/* Mapped at index 0x2022, subindex 0x01 - 0x08 */
extern UNS8 can2_BCUData_T2_3[8];		/* Mapped at index 0x2023, subindex 0x01 - 0x08 */
extern UNS8 can2_BCUData_MC2_1[8];		/* Mapped at index 0x2024, subindex 0x01 - 0x08 */
extern UNS8 can2_BCUData_MC2_2[8];		/* Mapped at index 0x2025, subindex 0x01 - 0x08 */
extern UNS8 can2_BCUData_MC2_3[8];		/* Mapped at index 0x2026, subindex 0x01 - 0x08 */
extern UNS8 can2_ATCData_MC1_1[7];		/* Mapped at index 0x2027, subindex 0x01 - 0x07 */
extern UNS8 can2_ATCData_MC1_2[8];		/* Mapped at index 0x2028, subindex 0x01 - 0x08 */
extern UNS8 can2_ATCData_MC1_3[8];		/* Mapped at index 0x2029, subindex 0x01 - 0x08 */
extern UNS8 can2_ATCData_MC1_4[4];		/* Mapped at index 0x202A, subindex 0x01 - 0x04 */
extern UNS8 can2_ATCData_MC2_1[7];		/* Mapped at index 0x202B, subindex 0x01 - 0x07 */
extern UNS8 can2_ATCData_MC2_2[8];		/* Mapped at index 0x202C, subindex 0x01 - 0x08 */
extern UNS8 can2_ATCData_MC2_3[8];		/* Mapped at index 0x202D, subindex 0x01 - 0x08 */
extern UNS8 can2_ATCData_MC2_4[4];		/* Mapped at index 0x202E, subindex 0x01 - 0x04 */
extern UNS8 can2_PISData_MC1_1[8];		/* Mapped at index 0x202F, subindex 0x01 - 0x08 */
extern UNS8 can2_PISData_MC1_2[3];		/* Mapped at index 0x2030, subindex 0x01 - 0x03 */
extern UNS8 can2_PISData_MC2_1[8];		/* Mapped at index 0x2031, subindex 0x01 - 0x08 */
extern UNS8 can2_PISData_MC2_2[3];		/* Mapped at index 0x2032, subindex 0x01 - 0x03 */
extern UNS8 can2_VVVF1Data_MC1_1[8];		/* Mapped at index 0x2033, subindex 0x01 - 0x08 */
extern UNS8 can2_VVVF1Data_MC1_2[6];		/* Mapped at index 0x2034, subindex 0x01 - 0x06 */
extern UNS8 can2_VVVF1Data_MC1_3[8];		/* Mapped at index 0x2035, subindex 0x01 - 0x08 */
extern UNS8 can2_VVVF1Data_MC1_4[8];		/* Mapped at index 0x2036, subindex 0x01 - 0x08 */
extern UNS8 can2_VVVF1Data_MC1_5[6];		/* Mapped at index 0x2037, subindex 0x01 - 0x06 */
extern UNS8 can2_VVVF2Data_MC1_1[8];		/* Mapped at index 0x2038, subindex 0x01 - 0x08 */
extern UNS8 can2_VVVF2Data_MC1_2[6];		/* Mapped at index 0x2039, subindex 0x01 - 0x06 */
extern UNS8 can2_VVVF2Data_MC1_3[8];		/* Mapped at index 0x203A, subindex 0x01 - 0x08 */
extern UNS8 can2_VVVF2Data_MC1_4[8];		/* Mapped at index 0x203B, subindex 0x01 - 0x08 */
extern UNS8 can2_VVVF2Data_MC1_5[6];		/* Mapped at index 0x203C, subindex 0x01 - 0x06 */
extern UNS8 can2_VVVF1Data_M_1[8];		/* Mapped at index 0x203D, subindex 0x01 - 0x08 */
extern UNS8 can2_VVVF1Data_M_2[6];		/* Mapped at index 0x203E, subindex 0x01 - 0x06 */
extern UNS8 can2_VVVF1Data_M_3[8];		/* Mapped at index 0x203F, subindex 0x01 - 0x08 */
extern UNS8 can2_VVVF1Data_M_4[8];		/* Mapped at index 0x2040, subindex 0x01 - 0x08 */
extern UNS8 can2_VVVF1Data_M_5[6];		/* Mapped at index 0x2041, subindex 0x01 - 0x06 */
extern UNS8 can2_VVVF2Data_M_1[8];		/* Mapped at index 0x2042, subindex 0x01 - 0x08 */
extern UNS8 can2_VVVF2Data_M_2[6];		/* Mapped at index 0x2043, subindex 0x01 - 0x06 */
extern UNS8 can2_VVVF2Data_M_3[8];		/* Mapped at index 0x2044, subindex 0x01 - 0x08 */
extern UNS8 can2_VVVF2Data_M_4[8];		/* Mapped at index 0x2045, subindex 0x01 - 0x08 */
extern UNS8 can2_VVVF2Data_M_5[6];		/* Mapped at index 0x2046, subindex 0x01 - 0x06 */
extern UNS8 can2_VVVF1Data_MC2_1[8];		/* Mapped at index 0x2047, subindex 0x01 - 0x08 */
extern UNS8 can2_VVVF1Data_MC2_2[6];		/* Mapped at index 0x2048, subindex 0x01 - 0x06 */
extern UNS8 can2_VVVF1Data_MC2_3[8];		/* Mapped at index 0x2049, subindex 0x01 - 0x08 */
extern UNS8 can2_VVVF1Data_MC2_4[8];		/* Mapped at index 0x204A, subindex 0x01 - 0x08 */
extern UNS8 can2_VVVF1Data_MC2_5[6];		/* Mapped at index 0x204B, subindex 0x01 - 0x06 */
extern UNS8 can2_VVVF2Data_MC2_1[8];		/* Mapped at index 0x204C, subindex 0x01 - 0x08 */
extern UNS8 can2_VVVF2Data_MC2_2[6];		/* Mapped at index 0x204D, subindex 0x01 - 0x06 */
extern UNS8 can2_VVVF2Data_MC2_3[8];		/* Mapped at index 0x204E, subindex 0x01 - 0x08 */
extern UNS8 can2_VVVF2Data_MC2_4[8];		/* Mapped at index 0x204F, subindex 0x01 - 0x08 */
extern UNS8 can2_VVVF2Data_MC2_5[6];		/* Mapped at index 0x2050, subindex 0x01 - 0x06 */
extern UNS8 can2_SIVData_T_1[7];		/* Mapped at index 0x2051, subindex 0x01 - 0x07 */
extern UNS8 can2_SIVData_T_2[8];		/* Mapped at index 0x2052, subindex 0x01 - 0x08 */
extern UNS8 can2_SIVData_T_3[3];		/* Mapped at index 0x2053, subindex 0x01 - 0x03 */
extern UNS8 can2_SIVData_T1_1[7];		/* Mapped at index 0x2054, subindex 0x01 - 0x07 */
extern UNS8 can2_SIVData_T1_2[8];		/* Mapped at index 0x2055, subindex 0x01 - 0x08 */
extern UNS8 can2_SIVData_T1_3[3];		/* Mapped at index 0x2056, subindex 0x01 - 0x03 */
extern UNS8 can2_ComnErr_MC1[2];		/* Mapped at index 0x2057, subindex 0x01 - 0x02 */
extern UNS8 can2_ComnErr_T[2];		/* Mapped at index 0x2058, subindex 0x01 - 0x02 */
extern UNS8 can2_ComnErr_M[2];		/* Mapped at index 0x2059, subindex 0x01 - 0x02 */
extern UNS8 can2_ComnErr_T1[2];		/* Mapped at index 0x205A, subindex 0x01 - 0x02 */
extern UNS8 can2_ComnErr_T2[2];		/* Mapped at index 0x205B, subindex 0x01 - 0x02 */
extern UNS8 can2_ComnErr_MC2[2];		/* Mapped at index 0x205C, subindex 0x01 - 0x02 */
extern UNS8 can2_TMSState_CCU1[5];		/* Mapped at index 0x205D, subindex 0x01 - 0x05 */
extern UNS8 can2_SetParaData_HMI[4];		/* Mapped at index 0x205E, subindex 0x01 - 0x04 */
extern UNS8 can2_GetFaultData_HMI1[2];		/* Mapped at index 0x205F, subindex 0x01 - 0x02 */
extern UNS8 can2_ParaData_HMI1_1[7];		/* Mapped at index 0x2060, subindex 0x01 - 0x07 */
extern UNS8 can2_ParaData_HMI1_2[8];		/* Mapped at index 0x2061, subindex 0x01 - 0x08 */
extern UNS8 can2_TempData_HMI[2];		/* Mapped at index 0x2062, subindex 0x01 - 0x02 */
extern UNS8 can2_ACCData_MC1_2;		/* Mapped at index 0x2063, subindex 0x00*/
extern UNS8 can2_ACCData_T_2;		/* Mapped at index 0x2064, subindex 0x00*/
extern UNS8 can2_ACCData_M_2;		/* Mapped at index 0x2065, subindex 0x00*/
extern UNS8 can2_ACCData_T1_2;		/* Mapped at index 0x2066, subindex 0x00*/
extern UNS8 can2_ACCData_T2_2;		/* Mapped at index 0x2067, subindex 0x00*/
extern UNS8 can2_ACCData_MC2_2;		/* Mapped at index 0x2068, subindex 0x00*/
extern UNS8 can2_GetFaultInfo_HMI1;		/* Mapped at index 0x2069, subindex 0x00*/
extern UNS8 can2_DeleteData_HMI1[3];		/* Mapped at index 0x206A, subindex 0x01 - 0x03 */
extern UNS8 can2_InitSetData_HMI1[8];		/* Mapped at index 0x206B, subindex 0x01 - 0x08 */
extern UNS8 can2_ParaData_HMI1_3[8];		/* Mapped at index 0x206C, subindex 0x01 - 0x08 */
extern UNS8 can2_ParaData_HMI1_4[8];		/* Mapped at index 0x206D, subindex 0x01 - 0x08 */
extern UNS8 can2_TMSDevData_CCU;		/* Mapped at index 0x206E, subindex 0x00*/
extern UNS8 can2_DoorData_MC1_34[8];		/* Mapped at index 0x206F, subindex 0x01 - 0x08 */
extern UNS8 can2_DoorData_T_34[8];		/* Mapped at index 0x2070, subindex 0x01 - 0x08 */
extern UNS8 can2_DoorData_M_34[8];		/* Mapped at index 0x2071, subindex 0x01 - 0x08 */
extern UNS8 can2_DoorData_T1_34[8];		/* Mapped at index 0x2072, subindex 0x01 - 0x08 */
extern UNS8 can2_DoorData_T2_34[8];		/* Mapped at index 0x2073, subindex 0x01 - 0x08 */
extern UNS8 can2_DoorData_MC2_34[8];		/* Mapped at index 0x2074, subindex 0x01 - 0x08 */
extern UNS8 can2_ATC_DateTime_MC2[6];		/* Mapped at index 0x2075, subindex 0x01 - 0x06 */
extern UNS8 can2_CCUData_CCU1;		/* Mapped at index 0x2076, subindex 0x00*/
extern UNS8 can2_CCUData_CCU2;		/* Mapped at index 0x2077, subindex 0x00*/
extern UNS8 can2_FaultDataCount_ERM[7];		/* Mapped at index 0x2078, subindex 0x01 - 0x07 */
extern UNS8 can2_AirPumpData_MC1_1[8];		/* Mapped at index 0x2079, subindex 0x01 - 0x08 */
extern UNS8 can2_AirPumpData_MC1_2[3];		/* Mapped at index 0x207A, subindex 0x01 - 0x03 */
extern UNS8 can2_AirPumpData_MC2_1[8];		/* Mapped at index 0x207B, subindex 0x01 - 0x08 */
extern UNS8 can2_AirPumpData_MC2_2[3];		/* Mapped at index 0x207C, subindex 0x01 - 0x03 */
extern UNS8 can2_CarArriveData_HMI1_1[2];		/* Mapped at index 0x207D, subindex 0x01 - 0x02 */
extern UNS8 can2_CarArriveData_HMI1_2[8];		/* Mapped at index 0x207E, subindex 0x01 - 0x08 */
extern UNS8 can2_TramCode_MC1[2];		/* Mapped at index 0x207F, subindex 0x01 - 0x02 */
extern UNS8 can2_TramCode_T[2];		/* Mapped at index 0x2080, subindex 0x01 - 0x02 */
extern UNS8 can2_TramCode_M[2];		/* Mapped at index 0x2081, subindex 0x01 - 0x02 */
extern UNS8 can2_TramCode_T1[2];		/* Mapped at index 0x2082, subindex 0x01 - 0x02 */
extern UNS8 can2_TramCode_T2[2];		/* Mapped at index 0x2083, subindex 0x01 - 0x02 */
extern UNS8 can2_TramCode_MC2[2];		/* Mapped at index 0x2084, subindex 0x01 - 0x02 */
extern UNS8 can2_DelResult_ERM[3];		/* Mapped at index 0x2085, subindex 0x01 - 0x03 */
extern UNS8 can2_SubDevFltData_MDU_1[7];		/* Mapped at index 0x2086, subindex 0x01 - 0x07 */
extern UNS8 can2_SubDevFltData_MDU_2[7];		/* Mapped at index 0x2087, subindex 0x01 - 0x07 */
extern UNS8 can2_SetDateTime_HMI[7];		/* Mapped at index 0x2088, subindex 0x01 - 0x07 */
extern UNS8 can2_GetFaultData_ERM[4];		/* Mapped at index 0x2089, subindex 0x01 - 0x04 */
extern UNS8 can2_SDRData_MC1;		/* Mapped at index 0x208A, subindex 0x00*/
extern UNS8 can2_SDRData_MC2;		/* Mapped at index 0x208B, subindex 0x00*/
extern UNS8 can2_BCUData_MC1_4;		/* Mapped at index 0x208C, subindex 0x00*/
extern UNS8 can2_BCUData_T_4;		/* Mapped at index 0x208D, subindex 0x00*/
extern UNS8 can2_BCUData_M_4;		/* Mapped at index 0x208E, subindex 0x00*/
extern UNS8 can2_BCUData_T1_4;		/* Mapped at index 0x208F, subindex 0x00*/
extern UNS8 can2_BCUData_T2_4;		/* Mapped at index 0x2090, subindex 0x00*/
extern UNS8 can2_BCUData_MC2_4;		/* Mapped at index 0x2091, subindex 0x00*/
extern UNS8 can2_PTU_CMD_ERM;		/* Mapped at index 0x2092, subindex 0x00*/
extern UNS8 can2_TMSState_CCU2[5];		/* Mapped at index 0x2093, subindex 0x01 - 0x05 */
extern UNS8 can2_CarData_HMI2[8];		/* Mapped at index 0x2094, subindex 0x01 - 0x08 */
extern UNS8 can2_DateTime_HMI2[7];		/* Mapped at index 0x2095, subindex 0x01 - 0x07 */
extern UNS8 can2_GetFaultData_HMI2[2];		/* Mapped at index 0x2096, subindex 0x01 - 0x02 */
extern UNS8 can2_ParaData_HMI2_1[7];		/* Mapped at index 0x2097, subindex 0x01 - 0x07 */
extern UNS8 can2_ParaData_HMI2_2[8];		/* Mapped at index 0x2098, subindex 0x01 - 0x08 */
extern UNS8 can2_GetFaultInfo_HMI2;		/* Mapped at index 0x2099, subindex 0x00*/
extern UNS8 can2_DeleteData_HMI2[3];		/* Mapped at index 0x209A, subindex 0x01 - 0x03 */
extern UNS8 can2_InitSetData_HMI2[8];		/* Mapped at index 0x209B, subindex 0x01 - 0x08 */
extern UNS8 can2_ParaData_HMI2_3[8];		/* Mapped at index 0x209C, subindex 0x01 - 0x08 */
extern UNS8 can2_ParaData_HMI2_4[8];		/* Mapped at index 0x209D, subindex 0x01 - 0x08 */
extern UNS8 can2_CarArriveData_HMI2_1[2];		/* Mapped at index 0x209E, subindex 0x01 - 0x02 */
extern UNS8 can2_CarArriveData_HMI2_2[8];		/* Mapped at index 0x209F, subindex 0x01 - 0x08 */
extern UNS8 can2_DIData_ERM[7];		/* Mapped at index 0x20A0, subindex 0x01 - 0x07 */
extern UNS8 can2_DoorData_MC1_56[8];		/* Mapped at index 0x20A1, subindex 0x01 - 0x08 */
extern UNS8 can2_DoorData_T_56[8];		/* Mapped at index 0x20A2, subindex 0x01 - 0x08 */
extern UNS8 can2_DoorData_M_56[8];		/* Mapped at index 0x20A3, subindex 0x01 - 0x08 */
extern UNS8 can2_DoorData_T1_56[8];		/* Mapped at index 0x20A4, subindex 0x01 - 0x08 */
extern UNS8 can2_DoorData_T2_56[8];		/* Mapped at index 0x20A5, subindex 0x01 - 0x08 */
extern UNS8 can2_DoorData_MC2_56[8];		/* Mapped at index 0x20A6, subindex 0x01 - 0x08 */
extern UNS8 can2_DoorData_MC1_78[8];		/* Mapped at index 0x20A7, subindex 0x01 - 0x08 */
extern UNS8 can2_DoorData_T_78[8];		/* Mapped at index 0x20A8, subindex 0x01 - 0x08 */
extern UNS8 can2_DoorData_M_78[8];		/* Mapped at index 0x20A9, subindex 0x01 - 0x08 */
extern UNS8 can2_DoorData_T1_78[8];		/* Mapped at index 0x20AA, subindex 0x01 - 0x08 */
extern UNS8 can2_DoorData_T2_78[8];		/* Mapped at index 0x20AB, subindex 0x01 - 0x08 */
extern UNS8 can2_DoorData_MC2_78[8];		/* Mapped at index 0x20AC, subindex 0x01 - 0x08 */
extern UNS8 can2_DoorCheckData_1[12];		/* Mapped at index 0x4000, subindex 0x01 */
extern UNS8 can2_ACPCheckData_1[4];		/* Mapped at index 0x4001, subindex 0x01 */
extern UNS8 can2_SIVCheckData_1[2];		/* Mapped at index 0x4002, subindex 0x01 */
extern UNS8 can2_BCUCheckData_1[130];		/* Mapped at index 0x4003, subindex 0x01 */
extern UNS8 can2_SpeedCheckData_1[13];		/* Mapped at index 0x4004, subindex 0x01 */
extern UNS8 can2_SpeedCheckData_2;		/* Mapped at index 0x4004, subindex 0x02 */
extern UNS8 can2_FaultInfo_ERM_1[20];		/* Mapped at index 0x4005, subindex 0x01 */
extern UNS8 can2_FaultInfo_ERM_2;		/* Mapped at index 0x4005, subindex 0x02 */
extern UNS8 can2_RunData_ERM_1[64];		/* Mapped at index 0x4006, subindex 0x01 */
extern UNS8 can2_SpeedData_ERM_1[13];		/* Mapped at index 0x400A, subindex 0x01 */
extern UNS8 can2_SpeedData_ERM_2;		/* Mapped at index 0x400A, subindex 0x02 */
extern UNS8 can2_FaultInfo_HMI_1[20];		/* Mapped at index 0x400B, subindex 0x01 */

#endif // CAN2OBJDICT_H
